server:
  port: 9080

spring:
  # Seguridad
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://k8s-lia.unrn.edu.ar/keycloak/realms/videoclub01
          jwk-set-uri: http://k8s-lia.unrn.edu.ar/keycloak/realms/videoclub/protocol/openid-connect/certs

  # Configuración de RabbitMQ
  rabbitmq:
    host: k8s-lia.unrn.edu.ar
    port: 30567
    username: taller
    password: taller.2024

  cloud:
    function:
      definition: keycloakEventProcessor;purchaseEventProcessor

    stream:
      default:
        content-type: application/json
      defaultBinder: rabbit
      bindings:
        purchaseEventProcessor-in-0:
          destination: eventvc01
          group: purchaseCouchDB01
        keycloakEventProcessor-in-0:
          destination: keycloaktaller
          group: compradorCouchDBVC01
      rabbit:
        bindings:
          keycloakEventProcessor-in-0:
            consumer:
              binding-routing-key: "KK.EVENT.*.videoclub01.#"
          purchaseEventProcessor-in-0:
            consumer:
              binding-routing-key: "VC01.EVENT.PURCHASE.#"

couchdb:
 # url: http://localhost:5984
  host: 127.0.0.1
  port: 5984
  username: admin
  password: admin
  database: compras
